module Trex
  module Train
    PARTREFUND_TRAIN =[
      "If you cancel or change your reservation before 0301 AM on 10/31/14 the hotel will charge you $27. If you cancel or change your reservation after 0301 AM on 10/31/14 the hotel will charge you $234. If you cancel or change your reservation after 0301 AM on 11/02/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 0530 AM on 07/13/15 the hotel will charge you $187. If you cancel or change your reservation after 0530 AM on 07/13/15 the hotel will charge you $540. If you cancel or change your reservation after 0530 AM on 07/15/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1201 AM on 05/23/16 the hotel will charge you $123. If you cancel or change your reservation after 1201 AM on 05/25/16 the hotel will charge you $382. If you cancel or change your reservation after 1201 AM on 05/25/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1201 AM on 10/21/14 the hotel will charge you $57. If you cancel or change your reservation after 1201 AM on 10/21/14 the hotel will charge you $333. If you cancel or change your reservation after 1201 AM on 10/24/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1700 PM on 06/05/13 the hotel will charge you $867. If you cancel or change your reservation after 1700 PM on 06/07/13 the hotel will charge you $1242. If you cancel or change your reservation after 1700 PM on 06/08/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 0600 AM on 04/12/14 the hotel will charge you $27. If you cancel or change your reservation after 0600 AM on 04/13/14  the hotel will charge you $154. If you cancel or change your reservation after 0600 AM on 04/13/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 0600 AM on 03/14/14 the hotel will charge you $82. If you cancel or change your reservation after 0600 AM on 03/15/14 the hotel will charge you $355. If you cancel or change your reservation after 0600 AM on 03/16/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 0201 AM on 01/31/14 the hotel will charge you $89. If you cancel or change your reservation after 0201 AM on 01/31/14 the hotel will charge you $335. If you cancel or change your reservation after 0201 AM on 02/31/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1501 PM on 12/28/14 the hotel will charge you $104. If you cancel or change your reservation after 1501 PM on 12/31/14 the hotel will charge you $1305. If you cancel or change your reservation after 1501 PM on 01/05/15  the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1201 AM on 03/04/15 the hotel will charge you $12. If you cancel or change your reservation after 1201 AM on 03/05/15 the hotel will charge you $25. If you cancel or change your reservation after 1201 AM on 03/07/15 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 2301 PM on 02/15/14 the hotel will charge you $134. If you cancel or change your reservation after 2301 PM on 02/17/14 the hotel will charge you $872. If you cancel or change your reservation after 2301 AM on 02/20/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1907 PM on 08/03/13 the hotel will charge you $97. If you cancel or change your reservation after 1907 PM on 08/05/13 the hotel will charge you $754. If you cancel or change your reservation after 1907 PM on 08/10/13 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1701 PM on 07/28/16 the hotel will charge you $57. If you cancel or change your reservation after 1701 PM on 07/29/16 the hotel will charge you $85. If you cancel or change your reservation after 1701 PM on 07/30/16 the hotel will charge you for the total cost of your reservation. ",
      "Cancellations or changes made before 4:00 PM Eastern Time on Sep 21, 2015 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 4:00 PM Eastern Time on Sep 21, 2015 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 6:00 PM Eastern Time on Jan 11, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 6:00 PM Eastern Time on Jan 11, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 4:00 AM Mountain Time on May 05, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 4:00 AM Mountain Time on May 05, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 6:00 AM Pacific Time on Feb 15, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 6:00 AM Pacific Time on Feb 15, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 8:00 PM Eastern Time on March 15, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 8:00 PM Eastern Time on March 15, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 8:00 PM Mountain Time on April 23, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 8:00 PM Mountain Time on April 23, 2014 are subject to a 2 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 4:00 PM Eastern Time on Dec 01, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 4:00 PM Eastern Time on Dec 01, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 4:00 PM Pacific Time on April 23, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 4:00 PM Pacific Time on April 23, 2014 are subject to a 2 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 5:00 AM Eastern Time on Dec 01, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 5:00 AM Eastern Time on Dec 01, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 12:00 AM Eastern Time on Oct 31, 2013 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 12:00 AM Eastern Time on Oct 31, 2013 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 12:00 AM Pacific Time on March 17, 2015 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 12:00 AM Pacific Time on March 17, 2015 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 12:00 PM Mountain Time on June 31, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 12:00 PM Mountain Time on June 31, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 4:00 PM Standard Time on Aug 12, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 4:00 PM Standard Time on Aug 12, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Cancellations or changes made before 4:00 PM Eastern Time on Nov 23, 2015 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 4:00 PM Eastern Time on Nov 23, 2015 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
    ]
  end
end
