module TeRex
  module Train
    AVAIL = [
      "A language code is needed for language translation.",
      "A maximum of 6 people are allowed to stay in the same room.",
      "A page ID is needed for language translation.",
      "A valid language code is needed for a translation request.",
      "Activity purchase required.",
      "All inventories were unsuccessful.",
      "Cannot book over 500 days in advance",
      "City could not be determined. LocationCode or (City and Country) are valid combinations",
      "DATA_VALIDATION",
      "Data in this request could not be validated: Multiple locations have been identified please refine your search criteria	",
      "Hotel has no overview information available.",
      "Hotel not found.",
      "Hotel not found.",
      "Incorrect XML format. Please check for missing elements or odd characters.",
      "Incorrect format for bed type preference.",
      "Incorrect value for star rating.",
      "Invalid Request",
      "Invalid or expired code.",
      "Invalid travel dates.",
      "Inventory Source Information Mismatch",
      "Minimum number of nights required.",
      "Must supply children age.",
      "NO_RESULTS_FOUND",
      "No vacancy.  Please try different dates or nearby hotels.",
      "No vacancy.",
      "Not found in database.",
      "PRICE_MISMATCH",
      "Please enter a city and/or state name for this search.",
      "Please enter a valid country code.",
      "Please enter a valid hotel ID.",
      "Please enter a valid state code.",
      "Please narrow down your search by entering additional criteria.",
      "Please narrow down your search by entering destination information for latitude and longitude searches.",
      "Please narrow this search by specifying more parameters.",
      "Please narrow your search by entering a city name.",
      "Please provide a check-in date or confirmation number for this search.",
      "Please provide a latitude decimal coordinate for this search.",
      "Please provide a longitude decimal coordinate for this search.",
      "Please provide decimal latitude and longitude coordinates for this search.",
      "Please provide one or more valid amenity codes for this search.",
      "Please try different dates or nearby hotels.",
      "Pricing error - we could not retrieve the rate information you requested at this time.",
      "Provider Message",
      "RECOVERABLE",
      "Refer to the Multiple Locations FAQ for details on recovering from these types of errors.",
      "Sorry you are not authorized to use this special offer code.",
      "Sorry you have not reached the minimum sale requirement to use this code.",
      "Specified arrival date is prior to today's date.",
      "Specified city could not be resolved as valid location",
      "Supplier Return Text is Null and Unparsable.",
      "Supplier id not recognized.",
      "The Guests tag is too large or too small based on what was specified in the Number Of Rooms tag.",
      "The Hotel Identifier is used along with any other identifier (locationID marketKeyword or Address).",
      "The amenity code is invalid.",
      "The chain code is invalid.",
      "The client request lacked location info in hotel shopping request.",
      "The client requests have bad end or depart/arrive dates.",
      "The client requests have bad start or begin or depart/arrive dates.",
      "The hotel you selected is no longer available. Please choose another. ",
      "The locale is not valid.",
      "The location cannot be solved by the market location service with the client request’s location info.",
      "The number of hotel guests exceeds the allowable number per hotel room.",
      "The number of rooms in the request is greater than 1.",
      "The rating code is invalid.",
      "The room type or rate you selected is no longer available. Please choose another. error.atlantis.priceMismatch",
      "The session has expired",
      "There are No Hotel solutions found for criteria specified.",
      "There is an error in your XML request. The structure is not correct the XML is not well formed and/or tags are not correctly created.	",
      "There must be at least one adult for every room or suite you reserve.",
      "This order-by-type query is not valid. Please try again.",
      "This product is currently not available. PRODUCT_UNAVAILABLE Requested product is not available.",
      "This request can not be processed because the specified arrival date is prior to today's date. Correct this information and try again",
      "This request can not be processed. 500 days advance is the maximum that can be searched. Try again ",
      "This request can not be processed. Choose another hotel and try again",
      "This request can not be processed. Try again",
      "This reservation can not be processed because it has more than 30 days. Correct this information and try again",
      "This sort-by-type query is not valid. Please try again.",
      "UNAUTHORIZED_REQUESTS DATA_VALIDATION 90047 The client made a request for which it does not have authorization.",
      "We cannot accept a reservation for longer than 30 days",
      "When client request does not include POS info.",
      "XML is not well formed ",
      "You can book only 1 or 2 rooms at a time.",
      "You have exceeded the maximum (100) number of hotels for your request.",
      "com.travelnow. supplier. hotel. merchant. translator. Translator Exception: RateDetail Service threw an exception.",
      "errors.supplier.hotel.nolonger error from supplier",
      "time_start OR time_end is not a valid date ('Y-m-d H:i:s' or 'Y-m-d')"
    ]
  end
end
