module TeRex
  module Train
    CANCEL = [
      "I AND CANCEL UC HOTEL SEGMENT 01", 
      "A record was missing in this process",
      "CANCELLED PRODUCT",
      "CANCELLED_PRODUCT",
      "Client not found in system.",
      "Hotel preCancel failed",
      "Unable to cancel reservation. An unknown error has occurred. Please call us for more information.",
      "MULTI ROOM PARTIAL CANCELLATION",
      "MULTI_ROOM_PARTIAL_CANCELLATION",
      "No Hotel Confirmation Number Found",
      "No HotelConfirmation Number Found",
      "Order is currently being processed",
      "PARTIAL CANCELLATION",
      "PRODUCT_UNAVAILABLE",
      "Please contact customer service.",
      "Please enter the customer's reservation confirmation number.",
      "Please try again later.",
      "Probably your reservation has already processed and cancelled. Please call us for more information.",
      "RES_NOT_FOUND",
      "Requested for product which is already cancelled.",
      "Reservation Not Cancelled.",
      "Reservation could not be found",
      "Reservation could not be retrieved.",
      "Reservation not found in system.",
      "The hotel confirmation information provided could not be resolved to a valid record",
      "The room(s) in this hotel reservation are not cancelled",
      "This product is currently not available",
      "This request has already processed and cancelled.",
      "This reservation could not be found.",
      "Unable to cancel reservation",
      "cannot find booking",
      "cannot find reservation",
      "com.orbitz.tbs.model.SystemException: Hotel preCancel failed",
      "com.orbitz.tbs.spi.txn.cancel.SpiProductPreCancelCriteria productType=Hotel",
      "error.order.currentProcessing.tryLater",
      "error.orderLine.notFound.",
      "error.orderNumber.notFound",
      "for.ordernum.orderguid.passed",
      "multiCurrencyDetails=\\n\\tat com.orbitz.tbs.hotel.mgr.HotelCancelServiceManager.handleHotelCancelException(HotelCancelServiceManager.java:634)\\n\\tat com.orbitz.tbs.hotel.mgr.HotelCancelServiceManager.preCancelMerchantBooking(HotelCancelServiceManager.java:322)\\n\\tat com.orbitz.tbs.hotel.mgr.HotelCancelServiceManager.preCancel(HotelCancelServiceManager.java:271)\\n\\tat com.orbitz.tbs.hotel.book.svc.HotelSpiReservationServiceImpl.preCancelProduct(HotelSpiReservationServiceImpl.java:913",
      "mystiquecancellation",
      "no booking found",
      "not found",
      "product already cancelled.",
      "productLocatorCode=",
      "reservation not found",
      "reservationStartDate=",
      "room not found",
      "this reservation has not been canceled"
    ]
  end
end
