module TeRex
  module Train
    CANCELFORBIDDEN = [
      "CANCEL DATE PASSED",
      "CANCELLATION DEADLINE PASSED",
      "CANCELLATION_DEADLINE_PASSED",
      "CANCEL_DATE_PASSED",
      "Hotel pre-cancel failed",
      "RES CANCELLED",
      "RES_CANCELLED",
      "Reservation cannot be cancelled online",
      "Reservation cannot be cancelled",
      "Reservation not cancelable or zero refund",
      "Too late to cancel reservation - deadline date has passed.",
      "Too late to cancel reservation -",
      "Too late to cancel reservation",
      "Unable to cancel reservation. Please contact customer service.",
      "Unable to cancel reservation. This reservation is pending. Please contact customer service.",
      "Unable to cancel reservation. This reservation was manually booked. Please contact customer service.",
      "Unable to cancel reservation.",
      "Unable to obtain cancellation number. Please contact customer service.",
      "booking cannot be cancelled online.",
      "booking cannot be cancelled.",
      "can not cancel",
      "cancellable",
      "cannot be cancelled.",
      "com.orbitz.tbs.model.txn.PolicyViolationException",
      "com.orbitz.ws.hotel.cancel.service.HotelCancelServiceImpl.buildHotelCancelResponse(HotelCancelServiceImpl.java:204)com.orbitz.ws.hotel.cancel.service.HotelCancelServiceImpl.execute(HotelCancelServiceImpl.java:160",
      "com.orbitz.ws.hotel.cancel.service.HotelCancelServiceImpl.buildMultiRoomCancelResponse(HotelCancelServiceImpl.java:288)",
      "com.orbitz.ws.tbs.ReservationServiceSupport.buildPreCancelFutureTaskResponse(ReservationServiceSupport.java:433)",
      "com.orbitz.ws.tbs.ReservationServiceSupport.callFutureTask(ReservationServiceSupport.java:313",
      "deadline date has passed",
      "error.ResModifyError: Changes are not allowed",
      "error.blockSpace",
      "error.cancel.orderline.",
      "error.nonRefundableBooking: Reservation is Non-Refundable.",
      "error.orderline.already.canceled",
      "multiple.notSupported",
      "mystiquecancellation",
      "no refund",
      "not cancelable",
      "not cancellable",
      "productPreCancelInfos cannot be null or empty",
      "reference your Itinerary Number if you have questions regarding the status of your reservation.",
      "uncancelable",
      "uncancellable",
      "zero refund"
    ]
  end
end

