module TeRex
  module Train
    CREDITDECLINE = [
      "Credit card transaction declined by CC clearing house",
      "Credit card transaction declined by credit card clearing house",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Card is on negative or block list\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:180)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:66)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:296",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Do Not Honor\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:180)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:66)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:296",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Do Not Honor\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:182)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.debit(DefaultOmpProcessor.java:59)\\n\\tat com.orbitz.tbs.host.txn.command.book.BookPaymentCommand.doDebit(BookPaymentCommand.java:58)\\n\\tat com.orbitz.tbs.host.txn.command.book.AbstractPaymentCommand.execute(AbstractPaymentCommand.java:144",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Expired Card\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:182)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:67)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:314)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.execute(BaseBookPaymentVerifyCommand.java:212",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Problem with account balance\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:182)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:67)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:314)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.execute(BaseBookPaymentVerifyCommand.java:212",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Referral - call local BA number\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:180)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:66)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:296",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Unknown could not identify\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:180)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:66)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:296",
      "This reservation can not be processed because your credit card was declined by CC clearing house.",
      "We're sorry but we were unable to process your request. You may have temporarily exceeded your credit or debit card limit. Please choose a different card and try again. errors.resInfo.cc.exceededCardLimit: MSTERR_TRAVCC_CARDERROR_LIMITEXCEEDED: 886",
      "We’re sorry but we were unable to process your request. You may have temporarily exceeded your credit or debit card limit. Please choose a different card and try again.",
      "error.creditCardDeclined. exceededCardLimit: Internal application error. :MessageReferenceId=UnknownMessageReferenceId. Exception=Credit card error status - LIMIT EXCEEDED(51). : CommonErrors::MSTError:886",
      "error.creditCardDeclined: CREDIT CARD DECLINE",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=Credit card error status - HOLDCARD(4). : CommonErrors::MSTError:873",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=Credit card error status - REFERRED (2). : CommonErrors::MSTError:872",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=credit card transaction referral-call by CC clearing house : CommonErrors::MSTError:500",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId.Exception=Credit card error status - REFUSED (5). : CommonErrors::MSTError:874",
      "error.creditCardDeclined:Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=credit card transaction declined by CC clearing house : CommonErrors::MSTError:502",
      "error.creditCardDeclined:Internal application error.:MessageReferenceId=UnknownMessageReferenceId.Exception=credit card transaction pickup (remove the card from user) by CC clearing house: CommonErrors::MSTError:503"
    ]
  end
end


