module TeRex
  module Train
    CREDITDECLINE = [
      "(remove the card from user)",
      "CREDIT CARD DECLINE",
      "Credit card transaction declined by CC clearing house",
      "Credit card transaction declined by credit card clearing house",
      "Exception=credit card transaction declined by CC clearing house : CommonErrors::MSTError:502",
      "Exception=credit card transaction referral-call by CC clearing house : CommonErrors::MSTError:500",
      "HOLDCARD(4)",
       "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=Invalid/missing subscriber name/merchant Id : CommonErrors::MSTError:504",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=Unknown failure : CommonErrors::MSTError:527",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=XML cannot be parsed by payment provider.: CommonErrors::MSTError:540",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId.Exception=Authorization network could not reach issuing bank. : CommonErrors::MSTError:553",
      "error.creditCardDeclined:Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=Internal error at payment provider - could be anything.: CommonErrors::MSTError:539",
      "error.creditCardDeclined:Internal application error.:MessageReferenceId=UnknownMessageReferenceId. Exception=Invalid/missing amount: CommonErrors::MSTError:506",
      "Internal application error.:MessageReferenceId=UnknownMessageReferenceId.Exception=Credit card error status - REFUSED (5). : CommonErrors::MSTError:874",
      "MessageReferenceId=UnknownMessageReferenceId. Exception=Credit card error status",
      "PAYMENT_FAILURE",
      "Payment Failure happened",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Do Not Honor",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Expired Card",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Problem with account balance",
      "Payment Failure happened. PAYMENT_FAILURE com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Referral - call local BA number",
      "REFERRED (2)",
      "This reservation can not be processed because your credit card was declined by CC clearing house.",
      "We're sorry but we were unable to process your request. You may have temporarily exceeded your credit or debit card limit. Please choose a different card and try again. errors.resInfo.cc.exceededCardLimit: MSTERR_TRAVCC_CARDERROR_LIMITEXCEEDED: 886",
      "We’re sorry but we were unable to process your request. You may have temporarily exceeded your credit or debit card limit. Please choose a different card and try again.",
      "account balance",
      "application error.:MessageReferenceId=UnknownMessageReferenceId",
      "at com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:180)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:66)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:296",
      "at com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:182)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.debit(DefaultOmpProcessor.java:59)\\n\\tat com.orbitz.tbs.host.txn.command.book.BookPaymentCommand.doDebit(BookPaymentCommand.java:58)\\n\\tat com.orbitz.tbs.host.txn.command.book.AbstractPaymentCommand.execute(AbstractPaymentCommand.java:144",
      "at com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.checkFailedAuth(DefaultOmpProcessor.java:182)\\n\\tat com.orbitz.tbs.host.txn.omp.DefaultOmpProcessor.validate(DefaultOmpProcessor.java:67)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.doValidate(BaseBookPaymentVerifyCommand.java:314)\\n\\tat com.orbitz.tbs.host.txn.command.book.BaseBookPaymentVerifyCommand.execute(BaseBookPaymentVerifyCommand.java:212",
      "by CC clearing house: CommonErrors::MSTError:503",
      "com.orbitz.tbs.model.txn.PaymentException: Bad Auth. Causing CreditAuthResult:Card is on negative or block list",
      "do not honor",
      "error.:MessageReferenceId=UnknownMessageReferenceId.Exception=credit card transaction pickup",
      "error.creditCardDeclined",
      "error.creditCardDeclined. exceededCardLimit: Internal application error. :MessageReferenceId=UnknownMessageReferenceId. Exception=Credit card error status - LIMIT EXCEEDED(51). : CommonErrors::MSTError:886",
      "error.creditCardDeclined: Internal application error",
      "error.creditCardDeclined: Internal application error.:MessageReferenceId=UnknownMessageReferenceId",
      "error.creditCardDeclined:Internal application",
      "error.creditCardDeclined:Internal",
      "expired card",
      "hold card",
      "holdcard",
      "mystiquebooking",
      "refused"
    ]
  end
end


