module TeRex
  module Train
    PARTREFUND = [
      "If you cancel or change your reservation before 1201 AM on 10/21/14 the hotel will charge you $57. If you cancel or change your reservation after 1201 AM on 10/21/14 the hotel will charge you $335. If you cancel or change your reservation after 1201 AM on 10/24/14 the hotel will charge you for the total cost of your reservation.",
      "If you cancel or change your reservation before 4:00 PM on 9/22/14, the hotel will charge you $388. If you cancel or change your reservation after 4:00 PM on 9/22/14, the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 1201 AM on 9/10/14 the hotel will charge you $225. If you cancel or change your reservation after 1201 AM on 9/10/14 the hotel will charge you for the total cost of your reservation.",
      "Cancellations or changes made before 4:00 PM Eastern Time on Sep 11, 2014 are subject to a 1 Night Room & Tax penalty. Cancellations or changes made after 4:00 PM Eastern Time on Sep 11, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
     "If you cancel or change your reservation before 3:00 PM on 07/14/14, the hotel will charge you $189. If you cancel or change your reservation after 3:00 PM on 07/14/14, the hotel will charge you $225. If you cancel or change your reservation after 3:00 PM on 07/17/14 the hotel will charge you for the total cost of your reservation. ",
      "If you cancel or change your reservation before 3:00 PM on 7\\/31\\/14, the hotel will charge you $305. If you cancel or change your reservation after 3:00 PM on 7\\/31\\/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 4:00 PM on 9/22/14, the hotel will charge you $245. If you cancel or change your reservation after 4:00 PM on 9/22/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 4:00 PM on 9/24/14, the hotel will charge you $233. If you cancel or change your reservation after 4:00 PM on 9/24/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 12:00 PM on 1/05/15, the hotel will charge you $86. If you cancel or change your reservation after 12:00 PM on 1/05/15, the hotel will charge you $625. If you cancel or change your reservation after 12:00 PM on 1/07/15 the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 4:00 PM on 9/21/14, the hotel will charge you $215. If you cancel or change your reservation after 4:00 PM on 9/21/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 6:00 PM on 04/17/14, the hotel will charge you $187. If you cancel or change your reservation after 6:00 PM on 04/17/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 16:00 PM on 3/31/14, the hotel will charge you $89. If you cancel or change your reservation after 16:00 PM on 3/31/14,, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 6:00 AM on 12/07/14, the hotel will charge you $5675. If you cancel or change your reservation after 6:00 AM on 12/07/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 3:00 PM on 07/14/14, the hotel will charge you $189. If you cancel or change your reservation after 3:00 PM on 07/14/14, the hotel will charge you $225. If you cancel or change your reservation after 3:00 PM on 07/17/14 the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 7:00 AM on 06/09/14, the hotel will charge you $509. If you cancel or change your reservation after 7:00 AM on 06/09/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 9:00 PM on 5/23/14, the hotel will charge you $1018. If you cancel or change your reservation after 9:00 PM on 5/23/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 10:00 PM on 5/31/14, the hotel will charge you $215. If you cancel or change your reservation after 10:00 PM on 5/31/14, the hotel will charge you $425. If you cancel or change your reservation after 10:00 PM on 6/03/14 the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 8:00 AM on 12/17/14, the hotel will charge you $15. If you cancel or change your reservation after 8:00 AM on 12/17/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 12:00 PM on 1/05/15, the hotel will charge you $86. If you cancel or change your reservation after 12:00 PM on 1/05/15, the hotel will charge you $625. If you cancel or change your reservation after 12:00 PM on 1/07/15 the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 2:00 PM on 11/14/14, the hotel will charge you $57. If you cancel or change your reservation after 2:00 PM on 11/14/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 2:00 PM on 11/14/14, the hotel will charge you $57. If you cancel or change your reservation after 2:00 PM on 11/14/14, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 12:00 PM on 1/05/15, the hotel will charge you $86. If you cancel or change your reservation after 12:00 PM on 1/05/15, the hotel will charge you $625. If you cancel or change your reservation after 12:00 PM on 1/07/15 the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 4:00 PM on 2/21/15, the hotel will charge you $115. If you cancel or change your reservation after 4:00 PM on 2/21/15, the hotel will charge you for the total cost of your reservation. ",
     "If you cancel or change your reservation before 4:00 PM on 2/14/15, the hotel will charge you $318. If you cancel or change your reservation after 4:00 PM on 2/14/15, the hotel will charge you for the total cost of your reservation. ",
    ]
  end
end
