module Trex
  module Train
    REFUND = [
      "Free cancellation before 1201 AM on 9/17/14! If you cancel or change your reservation after 1201 AM on 9/17/14 the hotel will charge you for the total cost of your reservation. ",
      "Free cancellation before 12:01 AM on 10/29/14! If you cancel or change your reservation after 12:01 AM on 10/29/14, the hotel will charge you $194. If you cancel or change your reservation after 12:01 AM on 10/30/14, the hotel will charge you for the total cost of your reservation.",
      "If you cancel or change your reservation after 12:01 AM on 9/12/14, the hotel will charge you for the total cost of your reservation. ",
      "Cancellations or changes made within 1 day prior to 4:00 PM local hotel time on the day of arrival are subject to a $142.93 charge. Cancellations or changes made after 4:00 PM local hotel time on the day of arrival are subject to a 100% charge. We are sorry but refunds are not available for early check-out.",
      "We understand that sometimes your travel plans change. We do not charge a change or cancel fee. However, this property (Courtyard by Marriott Traverse City) imposes the following penalty to its customers that we are required to pass on: Cancellations or changes made after 5:00 PM ((GMT-05:00) Eastern Time (US &amp; Canada)) on Jul 9, 2014 are subject to a 1 Night Room &amp; Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "Free cancellation before 800 PM on 9/20/14! If you cancel or change your reservation after 800 PM on 9/20/14 the hotel will charge you $158. If you cancel or change your reservation after 800 PM on 9/21/14 the hotel will charge you for the total cost of your reservation. ",
      "Any cancellation received within 2 days prior to arrival date will incur the first night charge. Failure to arrive at your hotel will be treated as a No-Show and will incur the first night charge (Hotel policy).",
      "For the room type you've selected you can cancel your reservation for a full refund up until noon on Friday September 12th (local hotel time). If you decide to cancel your reservation anytime between noon on Friday September 12th and noon on Saturday September 13th (local hotel time) the hotel requires payment for the first night's stay. You will be charged for the first night's stay including taxes and fees. Any remaining amount will be refunded to you. Refunds or cancellations are not available after noon local hotel time on your day of arrival (Saturday September 13th). ",
      "THIS PROPERTY REQUIRES A NOTIFICATION OF CANCELLATION BY 4PM HOTEL TIME 1 DAY PRIOR TO ARRIVAL TO AVOID A PENALTY.",
      "You can cancel free of charge up until the cancellation window. Cancellations or changes made after 4:00 PM Eastern Time on Sep 12, 2014 are subject to a 1 Night Room & Tax penalty. The property makes no refunds for no shows or early checkouts.",
      "For the room type you've selected you can cancel your reservation for a full refund up until noon on Monday September 15th (local hotel time). If you decide to cancel your reservation anytime between noon on Monday September 15th and noon on Wednesday September 17th (local hotel time) the hotel requires payment for the first night's stay. You will be charged for the first night's stay including taxes and fees. Any remaining amount will be refunded to you. Refunds or cancellations are not available after noon local hotel time on your day of arrival (Wednesday September 17th).",
      "-08FEB04 - END - CANCEL BY 0 DAYS PRIOR TO ARRIVAL, LOCAL HOTEL TIME TO AVOID A CANCELLATION PENALTY CANCEL POLICIES AND EARLY DEPARTURE FEES VARY BY HOTEL. SINCE A HOTEL CAN SET A CANCELLATION POLICY OF UP TO 30 DAYS IN ADVANCE PLEASE REVIEW POLICY PRIOR TO BOOKING TO AVOID POSSIBLE CHARGE.",
      "IF CANCELLATION IS NECESSARY, TO AVOID BILLING YOU MUST RECEIVE A CANCEL NUMBER BY 6 PM ON THE DATE OF ARRIVAL. CANCEL TIMES AND DATES MAY VARY. CONTACT THE RESERVED MOTEL 6 FOR SPECIFIC POLICIES THAT MAY AFFECT YOUR RESERVATION. . -EARLY CHECKOUT POLICY -CONTACT LOCATION FOR MORE INFORMATION. .",
      "-1800 HOTEL TIME, DAY OF ARRIVAL TO AVOID BILLING OF 1 NIGHT ROOM AND TAX OR FORFEITURE OF DEPOSIT",
      "RESERVATIONS MUST BE CANCELLED 1DAY/24HOURS PRIOR TO ARRIVAL TO AVOID A PENALTY OF ONE NIGHT ROOM AND TAX. INDIVIDUAL PLANS MAY HAVE VARING CANCEL POLICIES. EARLY DEPARTURE FEE 1NIGHTS STAY. .",
      "06NOV03 - END - CANCEL BY 1 DAYS PRIOR TO 1600 HOURS ON DAY OF ARRIVAL, LOCAL HOTEL TIME TO AVOID A CANCELLATION PENALTY CANCELLATION POLICY TEXT - DUE TO SEASONAL VARIATIONS, MOST ACCURATE CANCEL POLICY RETURNED UPON BOOKINGS.  INTERNATIONAL   MAXIMUM 3 ROOMS PER RESERVATION.  MAXIMUM 3 PERSONS PER ROOM ONLY IF A ROLLAWAY IS AVAILABLE.  DOMESTIC   MAXIMUM 5 ROOMS PER RESERVATIONS.  MAXIMUM 5 PERSONS PER ROOM ONLY IF ROLLAWAY IS AVAILABLE.",
      "RESERVATIONS MUST BE CANCELED *24 HOURS* PRIOR TO ARRIVAL DATE TO AVOID A PENALTY OF ONE NIGHT ROOM AND TAX CHARGE INDIVIDUAL PLANS MAY VARY SEE PLAN DISPLAY FOR MORE INFORMATION **100USD EARLY DEPARTURE FEE** .",
      "ALL RESERVATIONS MUST BE CANCELLED 24 HOURS PRIOR TO HOST TIME UNLESS DEPOSIT REQUIRED IF THIS RESERVATION HAS BEEN MADE ELECTRONICALLY PLEASE CANCEL IT ELECTRONICALLY TO AVOID CONFUSION AND A NO SHOW BILL. POLICY SUBJECT TO CHANGE. .",
      "ALL RESERVATIONS MUST BE CANCELLED 48 HOURS PRIOR TO ARRIVAL HOST TIME IF THIS RESERVATION HAS BEEN MADE ELECTRONICALLY PLEASE CANCEL IT ELECTRONICALLY TO AVOID CONFUSION AND A NO SHOW BILL POLICY SUBJECT TO CHANGE .",
      "IF CANCELLATION IS NECESSARY, TO AVOID BILLING YOU MUST RECEIVE A CANCEL NUMBER BY 6 PM ON THE DATE OF ARRIVAL. CANCEL TIMES AND DATES MAY VARY. CONTACT THE RESERVED MOTEL 6 FOR SPECIFIC POLICIES THAT MAY AFFECT YOUR RESERVATION. . -EARLY CHECKOUT POLICY -CONTACT LOCATION FOR MORE INFORMATION. .o",
      "RESERVATIONS MUST BE CANCELED *72 HOURS* PRIOR TO ARRIVAL LOCAL HOTEL TIME TO AVOID A PENALTY OF ONE NIGHT ROOM AND TAX CHARGE INDIVIDAUL PLANS MAY VARY SEE PLAN DISPLAY FOR MORE INFORMATION **75USD EARLY DEPARTURE FEE**",
      "- 12 NOON HOTEL TIME DAY OF ARRIVAL TO AVOID BILLING OF 1NT ROOM AND TAX OR FORFEITURE OF DEPOSIT",
      "RESERVATIONS MUST BE CANCELLED BY 1600/4PM DAY OF ARRIVAL LOCAL HOTEL TIME TO AVOID A PENALTY OF ONE NIGHT ROOM AND TAX CHARGE. NOTE- INDIVIDUAL PLANS MAY VARY. PLEASE READ INDIVIDUAL DISPLAY FOR MORE INFORMATION. **50.00USD EARLY DEPARTURE FEE** .",
      "- RESERVATIONS BOOKED 8 DAYS OR MORE PRIOR TO ARRIVAL MUST BE CANCELLED 7 DAYS PRIOR TO ARRIVAL TO RECEIVE REFUND - RESERVATIONS BOOKED WITHIN 7 DAYS OF ARRIVAL FORFEIT DEPOSIT OF 3 NIGHTS ROOM AND TAX",
      "ALL RESERVATIONS MUST BE CANCELLED 24 HOURS PRIOR TO HOST TIME UNLESS DEPOSIT REQUIRED IF THIS RESERVATION HAS BEEN MADE ELECTRONICALLY PLEASE CANCEL IT ELECTRONICALLY TO AVOID CONFUSION AND A NO SHOW BILL POLICY SUBJECT TO CHANGE .",
      "PLEASE REFER TO RATE DETAILS AT THE TIME OF BOOKING FOR CANCELLATION POLICY. PLEASE NOTE THAT POLICY IS SUBJECT TO CHANGES WITHOUT NOTICE."
    ]
  end
end
