module TeRex
  module Train
    UNEXPECTED = [
      "We're sorry but we're unable to process your request due to an unknown error.",
      "Supplier communication problem ",
      "3rd Party Error: Server responded with an error message.",
      "AGENT_ATTENTION",
      "AUTHENTICATION RECOVERABLE TravelNow.com cannot service this request. Authentication failure.  (cid=; ipAddress= )",
      "Access denied.",
      "Additional Agent Attention Is Required For This Reservation",
      "Bundle not found.",
      "COMMUNICATION",
      "Cached availability could not be found. Please reissue availability.",
      "Cannot connect to MTS driver.",
      "Connectivity or communication problem. Try the request again or contact us",
      "DIRECT CONNECT ERROR *I 0RCF OR ET NotProcessed BusinessLogic ERR.SWS.HOST.ERROR_IN_RESPONSE",
      "EXCEPTION",
      "Error unmarshaling the request using Fast Info Set.: com. expedia e3.es.legacy booking. service.Legacy Booking Exceptions:2<TNOWERROR_ATTR> <SUPPLIER _ERROR_ CODE> com. expedia. e3.es.legacy booking. service. Legacy Booking Exceptions:2 </SUPPLIER _ERROR_ CODE> </TNOWERROR_ATTR>",
      "Exception: java. lang. No Class Def Found Error: Could not initialize class com. hotels. framework. service. Service Locator",
      "Failed Lapsang Service Invocation. requestURL: http:\\/\\/member-ws1-002.cpeg.orbitz.net:10005\\/members\\/legacy\\/RQST?username= \\nrequestMethod: GET SERVER_ERROR Failed Lapsang Service Invocation. requestURL: http:\\/\\/member-ws1-002.cpeg.orbitz.net:10005\\/members\\/legacy\\/RQST?username= \\nrequestMethod: GET",
      "HRN_QUOTE_KEY_FAILURE",
      "Information required for processing this request could not be created. The requested itinerary has not been created no charges have been issued.",
      "Internal Error: Unable to merge array into xml template.  Error was thrown. (1)",
      "Internal application error.:",
      "Internal server error. SERVER_ERROR Internal server error.",
      "PROCESS_FAIL",
      "Please enter the correct access code.",
      "Problem getting detailed room avail for XML/WS.	Rate Detail threw an exception. Query ID was and PropID:",
      "Property ID is No Longer Available",
      "Property ID lookup failed for supplier ID HotelID Query can not proceed",
      "Query could not be created or located in session",
      "ROLLBACK_ON_TIMEOUT",
      "Return threshold exceeded.",
      "SUPPLIER_",
      "SUPPLIER_COMMUNICATION",
      "SYS_OFFLINE",
      "Sorry. Connectivity or communication problem. Try the request again or contact us",
      "Suitcase is empty.",
      "Supplier Communication Problem",
      "This request can not be processed. Try again",
      "This request can not be processed. Verify if all information are correct and try again",
      "Timeout exception occurred and RollbackOnTimeout = true. Order will be rolled back: 6994 The booking attempt timed out. Attempt the booking again if you receive this error.",
      "TravelNow.com cannot service this request. Authentication failure.  (cid=; ipAddress= )",
      "TravelNow.com cannot service this request. Authentication failure. (cid= ipAddress= )",
      "TravelNow.com cannot service this request. No Response Available.",
      "TravelNow.com cannot service this request. Please try again.",
      "TravelNow.com cannot service this request.",
      "TravelNow.com was unable to appropriately create back-end information required for this request.",
      "UNKNOWN",
      "UNRECOVERABLE",
      "Unable to cancel reservation. An unknown error has occurred. Please call us for more information.",
      "We're sorry but we're unable to process your request due to a backend connection failure. error.atlantis.connectionFailure",
      "We're sorry but we're unable to process your request due to a backend timeout.	error.atlantis.timeout",
      "We're sorry but we're unable to process your request due to an unknown error.	error.processFail:",
      "We're sorry but we're unable to process your request due to an unknown error. error.atlantis",
      "We're sorry but we're unable to process your request due to an unknown error. error.atlantis.invalidXML",
      "We're sorry but we're unable to process your request due to an unknown error. error.processFail: Connectivity or communication problem with OMS Connectivity or communication problem. Try the request again. In the event of an unexpected outage this may be an extended period.",
      "We're sorry but we're unable to process your request due to an unknown error. error.trip",
      "We're sorry but we're unable to process your request due to an unknown error.",
      "We're sorry an error occurred while you were managing your images. Please try again.",
      "We're sorry but you cannot access this resource.",
      "We're sorry but you don't have permission to run this report.",
      "com. travelnow. supplier. hotel. merchant. translator. Translator Exception: Rate Detail Service threw an exception. Query ID was and PropID:",
      "error. unknown: com. hotels. service. integration. javex. Javex Connection Exception: Javex Http Manager :: IO Exception	Connection to supplier database was lost.",
      "error.processFail",
      "error.unknown: Internal application error.: Message ReferenceId= Unknown Message ReferenceId. Exception = Hotel room type not found at this hotel. Please select a different room dates or or hotel.: Common Errors::MSTError: 180 <TNOWERROR_ATTR> <SUPPLIER_ERROR_CODE> Common Errors:: MSTError:180 </SUPPLIER_ERROR_CODE> </TNOWERROR_ATTR>",
      "java.lang.NullPointerException SERVER_ERROR",
      "null error. serverError: Generic Travel Server error Expedia server down",
      "suitcase empty",
    ]
  end
end
