module TeRex
  module Train
    UNEXPECTED = [
      "3rd Party Error: Server responded with an error message.",
      "AUTHENTICATION RECOVERABLE TravelNow.com cannot service this request. Authentication failure.  (cid=; ipAddress= )",
      "Access denied.",
      "Bundle not found.",
      "Cannot connect to MTS driver.",
      "Connectivity or communication problem. Try the request again or contact us",
      "EXCEPTION",
      "Exception: java. lang. No Class Def Found Error: Could not initialize class com. hotels. framework. service. Service Locator",
      "Failed Lapsang Service Invocation. requestURL: http:\\/\\/member-ws1-002.cpeg.orbitz.net:10005\\/members\\/legacy\\/RQST?username= \\nrequestMethod: GET SERVER_ERROR Failed Lapsang Service Invocation. requestURL: http:\\/\\/member-ws1-002.cpeg.orbitz.net:10005\\/members\\/legacy\\/RQST?username= \\nrequestMethod: GET",
      "HRN_QUOTE_KEY_FAILURE",
      "Internal Error: Unable to merge array into xml template.  Error was thrown. (1)",
      "Internal application error.:",
      "Internal server error. SERVER_ERROR Internal server error.",
      "No Response",
      "PROCESS_FAIL",
      "Please enter the correct access code.",
      "Query could not be created or located in session",
      "ROLLBACK_ON_TIMEOUT",
      "Return threshold exceeded.",
      "SYS_OFFLINE",
      "Sorry. Connectivity or communication problem. Try the request again or contact us",
      "Supplier communication problem",
      "This request can not be processed. Verify if all information are correct and try again",
      "This request can not be processed. Try again",
      "UNAUTHORIZED_REQUESTS The client made a request for which it does not have authorization.",
      "com.orbitz.tbs.model.SystemException: Unknown exception caught stack is: com.orbitz.lapsang.http.client.HttpInvocationRequestException: Failed Lapsang Service Invocation. requestURL: http://hbe-austin-axpt1-1.qa.orbitz.net:20201/hotel/book\\nrequestMethod",
      "This request can not be processed",
      "This request can not be processed. Verify if all information are correct and try again",
      "TravelNow.com cannot service this request. Authentication failure. (cid= ipAddress= )",
      "TravelNow.com was unable to appropriately create back-end information required for this request.",
      "UNKNOWN",
      "We're sorry but we're unable to process your request due to a backend connection failure. error.atlantis.connectionFailure",
      "We're sorry but we're unable to process your request due to a backend timeout. error.atlantis.timeout",
      "We're sorry but we're unable to process your request due to an unknown error. error.processFail:",
      "We're sorry but we're unable to process your request due to an unknown error. error.atlantis",
      "We're sorry but we're unable to process your request due to an unknown error. error.atlantis.invalidXML",
      "We're sorry but we're unable to process your request due to an unknown error. error.processFail: Connectivity or communication problem with OMS Connectivity or communication problem. Try the request again. In the event of an unexpected outage this may be an extended period.",
      "We're sorry but we're unable to process your request due to an unknown error. error.trip",
      "We're sorry but we're unable to process your request due to an unknown error.",
      "We're sorry an error occurred while you were managing your images. Please try again.",
      "We're sorry but you cannot access this resource.",
      "We're sorry but you don't have permission to run this report.",
      "cannot service this request.",
      "com.orbitz.tbs.model.SystemException: Unknown exception caught stack is: com.orbitz.command.CommandException: Unexpected error\\njava.lang.NoSuchMethodError: com.orbitz.proto.finance.fraudcheck.TransactionRequest$Builder.addHotelInfo(Lcom\\/orbitz\\/proto\\/finance\\/fraudcheck\\/HotelInfo$Builder;)Lcom\\/orbitz\\/proto\\/finance\\/fraudcheck\\/TransactionRequest$Builder;\\n\\n\\tat com.orbitz.command.CommandResponse.get(CommandResponse.java:49",
      "com.orbitz.tbs.model.SystemException: Unknown exception caught stack is: com.orbitz.lapsang.http.client.HttpInvocationRequestException: Failed Lapsang Service Invocation. requestURL: http:\\/\\/amexapp07q.qa.orbitz.net:20201\\/hotel\\/book\\nrequestMethod: POST\\n\\tat com.orbitz.lapsang.http.client.AbstractHttpInvocationHandler.doObject(AbstractHttpInvocationHandler.java:330)\\n\\tat com.orbitz.lapsang.http.client.AbstractHttpInvocationHandler.invoke(AbstractHttpInvocationHandler.java:186",
      "error. unknown: com. hotels. service. integration. javex. Javex Connection Exception: Javex Http Manager :: IO Exception	Connection to supplier database was lost.",
      "error.processFail",
      "java.lang.NullPointerException SERVER_ERROR",
      "null error. serverError: Generic Travel Server error Expedia server down",
      "We're sorry but we're unable to process your request due to a backend connection failure.",
      "We're sorry but we're unable to process your request due to a backend timeout",
      "We're sorry but we're unable to process your request due to an unknown error."
    ]
  end
end
