module TeRex
  module Train
    UNKNOWN = [
      "The cancellation policy will be determined when the rate is validated.",
      "-CANCEL POLICY MAY VARY BY DAY OF WEEK AND SEASON. THE MOST ACCURATE CANCEL POLICY IS ADVISED DURING BOOKING PROCESS.  IN CASE OF A NO-SHOW THE CREDIT CARD WILL BE CHARGED ONE NIGHT STAY.  OUR SYSTEM ACKNOWLEDGES ALL PROPERLY CANCELED RESERVATIONS BY RETURNING A CANCELLATION NUMBER. DO NOT ASSUME YOUR RESERVATION IS CANCELED IF YOU HAVE NOT RECEIVED A CANCELLATION NUMBER IN YOUR PNR OR BOOKING FILE. IF YOU DO NOT RECEIVE A CANCELLATION NUMBER, PLEASE CALL THE CHOICE GDS DEPARTMENT AT 1-866-953-4570",
      "CANCELLATION DEADLINES MAY VARY BY DATES OF ARRIVAL/ SPECIAL EVENTS OR BY RATE PLAN. PLEASE READ THE RATE RULES FOR YOUR RESERVATION FOR THE EXACT DEADLINE. FAILURE TO CANCEL WITHIN THE DEADLINE WILL RESULT IN A CANCELLATION FEE THAT COULD RANGE FROM 1 NIGHT UP TO THE TOTAL AMOUNT OF STAY. NON REFUNDABLE RATES CANNOT BE CANCELLED AND ARE SUBJECT TO FULL AMOUNT OF STAY PENALTY. -EARLY CHECKOUT POLICY -NO CHARGE FOR EARLY DEPARTURE AS LONG AS THE GUEST CHECKS OUT BY 12PM EASTERN STANDARD TIME -EXCEPTIONS MAY APPLY DURING SPECIAL EVENTS OR CONVENTIONS - SEE RATE RULES.",
      "-14JAN02 - END - CANCEL POLICIES VARY BY HOTEL.  SINCE A HOTEL CAN SET A CANCELLATION POLICY OF UP TO 30 DAYS IN ADVANCE, PLEASE REVIEW POLICY PRIOR TO BOOKING TO AVOID POSSIBLE CHARGE."
    ]
  end
end
